micronaut:
  application:
    name: petsdb

configuration:
  mysql:
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    hostname: "${DB_HOSTNAME}"

#  sauron:
#    url: "${SAURON_URI}"
#    user: "${SAURON_USER}"
#    password: "${SAURON_PASSWORD}"